# Generated by Django 5.0.4 on 2024-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ame', models.CharField(max_length=25)),
                ('e_mail', models.EmailField(max_length=25)),
                ('p_hone', models.CharField(max_length=25)),
            ],
        ),
    ]
