# Generated by Django 5.0.4 on 2024-05-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
