# Generated by Django 5.0.4 on 2024-06-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diettrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=25)),
                ('Meal', models.CharField(max_length=25)),
                ('Calories', models.CharField(max_length=25)),
                ('Height', models.CharField(max_length=25)),
                ('Weight', models.CharField(max_length=25)),
                ('WaterIntake', models.CharField(max_length=25)),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
    ]
