# Generated by Django 5.0.4 on 2024-06-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_diettrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diettrack',
            old_name='Calories',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='Meal',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='WaterIntake',
            new_name='waterintake',
        ),
        migrations.RenameField(
            model_name='diettrack',
            old_name='Weight',
            new_name='weight',
        ),
    ]
